### ISSUE TITLE
Wrong comparison of access rights

### ISSUE THREAD

**Issue by tboeckel** [lammertb/libfins#22]
The function XX_finslib_search_area() does a wrong comparison of the access rights.

Currently line 164 of fins_search.c looks like this:
`if ( ( fins_area[a].access | accs )    == 0x00000000            ) { a++; continue; }`

The possible access modes and the requested access more are logically OR'ed and compared to be non-zero. This cannot work, because OR'ing two non-zero values will always result in a non-zero value again. Hence this check will never cause an entry to be skipped.

This is how the check must be done by AND'ing the two values:
`if ( ( fins_area[a].access & accs )    == 0x00000000            ) { a++; continue; }`

If the defined access rights and the requested access rights have a zero intersection, then this entry cannot be used and must be skipped. If the intersection is non-zero then the access is allowed.

**Comment by lammertb** [comment]
Thanks for the correction. The source code has been fixed with your recommendation in commit    https://github.com/lammertb/libfins/commit/3cadf5565dfc5333768e7d7e8f9970f81f7063dd
