### ISSUE TITLE
make makefile

### ISSUE THREAD

**Issue by ghost** [lammertb/libfins#5]
When trying to run the makefile from command prompt:
include/vcruntime.h(47): fatal error C1083: Cannot open include file: 'sal.h': No such file or directory

I've copied the missing header files in the include directory of the libfins-master forlder and that pretty much solve this issue of missing the header files.

After this, the next error: 
include/crtdefs.h(414): warning C4005: '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_0_EX': macro redefinition
include/corecrt.h(1824): note: see previous definition of '__DEFINE_CPP_OVERLOAD_STANDARD_FUNC_0_0_EX'

I've solved this by commenting on one of the header files one of the "#define".

My last error is this :
include/crtdefs.h(431): error C2371: '_locale_t': redefinition; different basic types
include/corecrt.h(529): note: see declaration of '_locale_t' .

Is it correct the way I solved the issues that I had, or in the makefile I should put the path of those missing header files so that when compiling in command prompt to get the .lib file that I need.

Thank you.

**Comment by lammertb** [comment]
According to the error messages, you seem to be compiling on a Windows system. But without known the development environment and version, this error is difficult to reproduce.

**Comment by lammertb** [comment]
OP didn't provide the required extra information about the environment. The issue is therefore closed.
