### ISSUE TITLE
I need example code to write data to DM and EM.

### ISSUE THREAD

**Issue by greenbaypayment** [lammertb/libfins#8]
I know if we are going to write data to CIO register, must describe like finslib_memory_area_write_uint16(sys, "CIO100.0", addr, num) .
But if we are going to write data to DM or EM, how can we describe memory name ?
"D0.0" or "E0.0" -> Such describe was occurred error by me. 
If you would provide example code, I will be happy. 
Look forward to hear from you soon
Thanks

**Comment by lammertb** [comment]
You can't write a single bit with the finslib_memory_area_write_uint16() function, only full words. D0.0 and E0.0 represent single bits.
